### ISSUE TITLE
commandResult.exitCode return -1

### ISSUE THREAD

**Issue by VikramSN** [jaredrummler/AndroidShell#10]
<b> I am trying to get hash value using MD5sum using Shell.SU.run() method.
but the result always returns -1, and isSuccessful() method not called.
</b>
<pre>
       var result:String? = null
        val hashCommand = Shell.SU.run("md5sum $path")
        Log.d("getHash", "Path : $path, Before : " + hashCommand.stdout.toString() + ", Error : " + hashCommand.stderr + ", Exit Code : " + hashCommand.exitCode)
        if (hashCommand.isSuccessful) {
            result =  hashCommand.stdout.toString()
            Log.d("getHash", "Path : $path, Success : " + hashCommand.stdout.toString() + ", Error : " + hashCommand.stderr)
        }
        Log.d("getHash", "Path : $path, Last : " + hashCommand.stdout.toString() + ", Error : " + hashCommand.stderr + ", Exit Code : " + hashCommand.exitCode)
       
</pre>

**Comment by MuntashirAkon** [comment]
Same happened to me for another command. Probably because of some underlying bugs.

**Comment by jaredrummler** [comment]
Please try the updated library as it has been re-written. See README for more info. Closing for now but will re-open if issues persist.
