### ISSUE TITLE
pm unistall is not working

### ISSUE THREAD

**Issue by petrovichtim** [jaredrummler/AndroidShell#2]
Remove system app is failed
 CommandResult result = Shell.SU.run("pm uninstall " + ai.packageName);
return "Failed" on rooted device

**Comment by jaredrummler** [comment]
Try setting the environment variable `LD_LIBRARY_PATH`. I remember having a similar issue years ago. I don't have time to dive into this but if you google "LD_LIBRARY_PATH android root" you should probably find more info.
