### ISSUE TITLE
Basic Usage returns me permission denied

### ISSUE THREAD

**Issue by victorjaviermartin** [jaredrummler/AndroidShell#23]
Hi @jaredrummler,

I'm trying this command:

```
val shell = Shell("sh")  // or sh -l
val result = shell.run("ls") 
if (result.isSuccess) {
    println(result.stdout())
}
```

and it's returning me on the stderr an error of permission denied.

Whats wrong?

thank you

**Comment by jrvansuita** [comment]
Are you receiving `sh: <stdin>[1]: adb: inaccessible or not found`?

**Comment by jaredrummler** [comment]
`ls` command is returning permission denied because the app doesn't have access to list the contents of the root directory.
