### ISSUE TITLE
OnCommandResultListener.onCommandResult() is called prematurely

### ISSUE THREAD

**Issue by Human** [jaredrummler/AndroidShell#4]
I'm using AndroidShell for an rsync app, and almost immediately after invoking rsync, the OnCommandResultListener that I pass to Shell.Builder.open() has its onCommandResult() called. The command can continue running for several minutes thereafter. I see the same behavior if I run "top" instead of "rsync" so it doesn't appear to be tied to any specific long-running command.

**Comment by Human** [comment]
Some further experimentation shows that an OnCommandResultListener passed to addCommand() doesn't return until the shell command completes, which is what I expected. I don't know if this is by design or not, but it's at the very least a workaround.

**Comment by jaredrummler** [comment]
Please see the updated library
