### ISSUE TITLE
Continuesly reading command output

### ISSUE THREAD

**Issue by aminehmida** [jaredrummler/AndroidShell#6]
First, thank you for this valuable lib!

I want to run a command, keep it running in the background and read the from stdout/stderr.

Is this something I can do with this libs? I have been looking at the code but I couldn't find out how to do that.

**Comment by jaredrummler** [comment]
I updated the library and you could do the following to achieve this:

```kotlin
val shell = Shell.SH
shell.addOnStdoutLineListener(object : Shell.OnLineListener {
  override fun onLine(line: String) {
      // do something
  }
})
```

Each time you run a command you will get any output in the above callback.
