### ISSUE TITLE
How to set Device Owner

### ISSUE THREAD

**Issue by amiyo-biswas** [jaredrummler/AndroidShell#8]
How can I execute below permissions 

` val result = Shell.SH.run("adb shell dpm set-device-owner com.app.test/.AppAdminReceiver") as CommandResult
`

**Comment by jaxn** [comment]
This isn't really an issue with the AndroidShell package, but...

You don't need to include `adb shell`, and you will need to run the command via SU.

`val result = Shell.SU.run("dpm set-device-owner com.app.test/.AppAdminReceiver") as CommandResult`
