### ISSUE TITLE
Shell.Builder Class

### ISSUE THREAD

**Issue by VikramSN** [jaredrummler/AndroidShell#9]
Please provide an example that how to use Shell.builder() class, and how to reset shell
or How to use multiple commands at once using this library.

**Comment by VikramSN** [comment]
I have found an easy way to use multiple commands in your library.
<pre>
after using Shell.SU.run("my_command")
I just used Shell.SU.closeConsol()
and then use again Shell.Su.run("next_command") for next command.
</pre>

<b>Example</b>
<pre>
val result = Shell.SU.run("AT")
if(result.isSuccessfull) {
Shell.SU.closeConsole()
val result1 = Shell.SU.run("cat /path")
}
</pre>

Thank you so much
This library is awesome and made by awesome peoples.

**Comment by jaredrummler** [comment]
Please see the README as I re-wrote the library and added more documentation. Let me know if you have further questions.
